### ISSUE TITLE
Not follows the minimap's border

### ISSUE THREAD

**Issue by Meilinn** [pereira-a/MBB#21] opened 2022-10-28 21:01 UTC
The button just makes a circle that it's smaller than the minimap, passing through the middle of the minimap and very outside of it. 
![Screenshot_107](https://user-images.githubusercontent.com/1574497/198731671-e76e9a34-b90f-41c8-87bb-a3273f1243bc.png)
![Screenshot_108](https://user-images.githubusercontent.com/1574497/198731712-86580fbf-d61f-4fb1-b8cd-2050d7e2611b.png)

**Comment by pereira-a** [comment] 2022-10-28 21:09
This is caused by the new HUD changes made by blizzard and released in this pre-patch. 

Meantime solution: ctrl + right-click the MBB icon so you can freely move the icon

**Comment by Meilinn** [comment] 2022-10-28 22:19
Thank you, I'll try that

**Comment by pereira-a** [comment] 2022-10-31 14:09
The latest release fixed this issue. Please update the addon and try it.
https://github.com/pereira-a/MBB/releases/tag/4.0.15-release
https://www.curseforge.com/wow/addons/minimapbuttonbag-reborn-mmb-reborn/files/4059864

**Closed as completed by pereira-a** 2022-10-31 14:09 UTC
Labels: bug, done
