### ISSUE TITLE
Dungeon / Battleground Queue button under MBB since today

### ISSUE THREAD

**Issue by KayM1** [pereira-a/MBB#28] opened 2022-12-04 14:14 UTC
The green dragon eye that pops up on the minimap for dungeon or bg / arena queues now also seems to be getting grouped under MBB. This makes it hard to see if you're queued or not + it also makes the LFD button functionality itself no longer work.

**Comment by pereira-a** [comment] 2022-12-04 15:18
This behavior does not happen to me. Maybe you have some addon that transforms the "Dragon eye" into a minimap button?

**Comment by Franky651** [comment] 2022-12-05 07:40
same issue here, the only other addon that I have and works with the buttons of the minimap is elvui.
reloading fix temporary the issue, till the next "queue is used"

**Comment by KayM1** [comment] 2022-12-05 09:07
I'm using ElvUI as well.

The only other new addon I installed that day was "Kaliel's Tracker (Dragonflight)"

**Comment by pyyzz** [comment] 2022-12-06 10:35
Really easy fix for this if you're remotely comfortable editing a file.

Open MBB.lua

Change line 96 from: 

`	[35] = "QueueStatusMinimapButton",`

to

`	[35] = "QueueStatusButton",`

**Comment by pereira-a** [comment] 2022-12-08 11:46
I confirm it is caused by ElvUI. For some reason, ElvUI decided to change the name of the status button. I'm adding that new name to the ignore list. The next update shall resolve this.

https://github.com/pereira-a/MBB/releases/tag/4.0.18-release

**Closed as completed by pereira-a** 2022-12-08 11:46 UTC
Labels: bug

**Comment by teelolws** [comment] 2023-02-02 08:26
ElvUI didn't change the name of the button, Blizzard changed it in 10.0. Probably because its not pinned to the Minimap anymore - ElvUI is pinning it to the minimap itsself.
